#!/usr/bin/env python3
"""
Generate docs/golden-vectors.json from the independent oracle (tools/reference/ref_calcs.py).

    python3 tools/reference/gen_golden.py           write docs/golden-vectors.json
    python3 tools/reference/gen_golden.py --check   exit 1 if the committed file differs from regenerated output

Deterministic: fixed key order, full float repr, UTF-8, LF newlines, trailing newline. Statuses are read
from docs/sources/LEDGER.md (never typed by hand), so a ledger change shows up as a --check failure.
This script never imports or reads src/.
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)
import ref_calcs  # noqa: E402

LEDGER_MD = os.path.join(ROOT, "docs", "sources", "LEDGER.md")
OUT = os.path.join(ROOT, "docs", "golden-vectors.json")
ID_RE = re.compile(r"S-\d{3}[a-z]?")
# Worst-first ordering used to collapse several ledger rows into one vector status.
SEVERITY = ["PAYWALLED-USER-MUST-VERIFY", "CONFLICT", "UNVERIFIED", "VERIFIED"]

NOTE = (
    "GENERATED by tools/reference/gen_golden.py from tools/reference/ref_calcs.py; do not edit by hand "
    "(CI runs gen_golden.py --check). Constants: rho20 1.7241e-8 and alpha 0.00393 (S-004); foil 35 um per "
    "oz/ft2 is a chosen convention (S-003, CONFLICT). oracle_value is the oracle's computed value "
    "(formula vs constants), NOT independent verification of any standard. 'status' is the worst status "
    "among the vector's ledger rows as read from docs/sources/LEDGER.md; UNLEDGERED means a constant has "
    "no ledger row yet; NOT-APPLICABLE means pure geometry."
)


def read_ledger():
    """Returns ({id: status}, [(lo, hi, status)]) parsed from the ledger markdown tables."""
    rows, ranges = {}, []
    status_col = -1
    with open(LEDGER_MD, encoding="utf-8") as fh:
        for line in fh.read().splitlines():
            if not line.strip().startswith("|"):
                status_col = -1
                continue
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            ids = ID_RE.findall(cells[0])
            if not ids:
                if "Status" in cells:
                    status_col = cells.index("Status")
                continue
            status = cells[status_col if status_col >= 0 else -1]
            for i in ids:
                rows[i] = status
            if len(ids) >= 2:
                ranges.append((int(ids[0][2:5]), int(ids[-1][2:5]), status))
    return rows, ranges


def status_of(i, rows, ranges):
    if i in rows:
        return rows[i]
    n = int(i[2:5])
    for lo, hi, st in ranges:
        if lo <= n <= hi:
            return st
    return "MISSING-FROM-LEDGER"


def build():
    rows, ranges = read_ledger()
    vectors = []
    for name, got, want, rtol, ids, note in ref_calcs.GOLDEN:
        ledger_status = {i: status_of(i, rows, ranges) for i in ids}
        if "UNLEDGERED" in note:
            status = "UNLEDGERED"
        elif not ids:
            status = "NOT-APPLICABLE"
        else:
            vals = list(ledger_status.values())
            status = next((s for s in SEVERITY if s in vals), vals[0])
        vectors.append({
            "name": name,
            "oracle_value": got,
            "pinned_expected": want,
            "rel_tol": rtol,
            "ledger_ids": list(ids),
            "ledger_status": ledger_status,
            "status": status,
            "note": note,
        })
    return {"note": NOTE, "vectors": vectors}


def render():
    return json.dumps(build(), indent=2, ensure_ascii=False) + "\n"


def main():
    text = render()
    if "--check" in sys.argv:
        try:
            with open(OUT, "rb") as fh:
                have = fh.read().replace(b"\r\n", b"\n")
        except FileNotFoundError:
            print(f"FAIL {OUT} missing; run tools/reference/gen_golden.py")
            sys.exit(1)
        if have != text.encode("utf-8"):
            print("FAIL docs/golden-vectors.json differs from regenerated output; "
                  "run python3 tools/reference/gen_golden.py and commit the result")
            sys.exit(1)
        print("OK   docs/golden-vectors.json matches the oracle")
        return
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print(f"wrote {OUT} ({len(ref_calcs.GOLDEN)} vectors)")


if __name__ == "__main__":
    main()
